fix iso installer

diff --git a/config/general/isolinux/attendedinstaller b/config/general/isolinux/attendedinstaller
--- a/config/general/isolinux/attendedinstaller
+++ b/config/general/isolinux/attendedinstaller
@@ -2,13 +2,16 @@
 # Copyright (c) Microsoft Corporation.
 # Licensed under the MIT License.
 
+set -o pipefail
+
 ISO_ROOT=/cdrom
 CONFIG_ROOT=$ISO_ROOT/config
 CACHE_REPO=$ISO_ROOT/cache-repo
+INSTALLER_LOG=/tmp/live-installer-attended.log
 
 # Mounting the ISO root for the installer.
 mkdir -p $ISO_ROOT
-LABEL=OIC_CDROM
+LABEL=ICT_CDROM
 
 function retry {
     local retry=0
@@ -51,8 +54,9 @@ stty -echo
 # Disable kernel messages on the current terminal
 dmesg -D
 
-live-installer --config $TEMPLATE_DUMP_YAML --repo $CACHE_REPO --attended
-installerExitCode=$?
+echo "Saving installer debug log to $INSTALLER_LOG"
+live-installer --config $TEMPLATE_DUMP_YAML --repo $CACHE_REPO --attended --log-level debug 2>&1 | tee -a "$INSTALLER_LOG"
+installerExitCode=${PIPESTATUS[0]}
 
 # Consume any buffered stdin to prevent it from being passed to any future programs,
 # as it may contain sensitive data
@@ -70,5 +74,6 @@ dmesg -E
 if [ $installerExitCode -eq 0 ]; then
     reboot
 else
+    echo "Installer failed. Debug log saved at $INSTALLER_LOG"
     /bin/bash
 fi
